apiVersion: v1
kind: ConfigMap
metadata:
  name: my-website-config
  namespace: nginx-site
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>GitOps Demo</title></head>
    <body style="background-color: #2d3436; color: white; text-align: center; padding-top: 50px;">
      <h1>Michael is the man!</h1>
      <p>Deployed via ArgoCD</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: argo-service
  namespace: nginx-site
spec:
  type: Loadbalancer
  selector:
    app: nginx-site
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-site
  namespace: nginx-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-site
  template:
    metadata:
      labels:
        app: nginx-site
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: website-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: website-content
          configMap:
            name: my-website-config
